# LG washer-dryer
- id: 'washer_notification'
  alias: Washer notification
  description: Alert when washer finishes
  trigger:
  - entity_id: binary_sensor.pralka_wash_completed
    platform: state
    from: 'off'
    to: 'on'
  condition: []
  action:
  - data:
      title: 'Pranie skończone!'
      message: 'Wyjmij pranie póki jest ciepłe!'
    service: notify.notify
