# B-METERS
- platform: template
  sensors:
    total_water:
      friendly_name: Total water
      unit_of_measurement: 'm³'
      value_template: "{{ states('sensor.bmeters_xxxxx') | float + states('sensor.bmeters_xxxxx') | float + states('sensor.bmeters_xxxxx') | float + states('sensor.bmeters_xxxxx') | float }}"

# QNAP SENSORS
- platform: qnap
  host: !secret qnap_ip
  verify_ssl: false
  username: !secret qnap_user
  password: !secret qnap_pass
  monitored_conditions:
    - status
    - system_temp
    - cpu_temp
    - cpu_usage
    - memory_free
    - memory_used
    - memory_percent_used
    - network_link_status
    - network_tx
    - network_rx
    - drive_smart_status
    - drive_temp
    - volume_size_free
    - volume_size_used
    - volume_percentage_used


# Philips led sensor
- platform: template
  sensors:
    led_senor_battery_level:
      friendly_name: "Led sensor battery level"
      value_template: "{{ state_attr('sensor.led_sensor_temperature', 'battery_level') }}"
      unit_of_measurement: "%"

# Xiaomi Roborock S6
- platform: template
  sensors:
    vacuum_status:
      friendly_name: Status
      entity_id:
        - vacuum.roborock_s6
      value_template: 'Status: {{ states.vacuum.roborock_s6.attributes.status }}'
      icon_template: >
        {% set val =  states.vacuum.roborock_s6.attributes.status  %}
        {% if val == 'Charging' %}
          mdi:battery-charging
        {% elif val == 'Cleaning' %}
          mdi:move-resize
        {% elif val == 'Returning home' %}
          mdi:keyboard-return
        {% elif val == 'Idle' %}
          mdi:dots-horizontal
        {% elif val == 'Paused' %}
          mdi:pause-circle
        {% else %}
          mdi:help-circle
        {% endif %}
    vacuum_fan_speed:
      friendly_name: Fan Speed
      entity_id:
        - vacuum.roborock_s6
      value_template: 'Mode: {{ states.vacuum.roborock_s6.attributes.fan_speed }}'
      icon_template: 'mdi:speedometer'
    vacuum_battery:
      friendly_name: Vacuum Battery
      entity_id:
        - vacuum.roborock_s6
      value_template: 'Battery: {{ states.vacuum.roborock_s6.attributes.battery_level }}'
      unit_of_measurement: '%'
      icon_template: '{{ states.vacuum.roborock_s6.attributes.battery_icon }}'
    vacuum_cleaned_area:
      friendly_name: Area of Last Cycle
      unit_of_measurement: 'm²'
      entity_id:
        - vacuum.roborock_s6
      value_template: "{{ states('sensor.roborock_s6_last_clean_area') | float | round(2) }}"
      icon_template: 'mdi:ruler'
    vacuum_total_cleaned_area:
      friendly_name: Total area of cleaning
      unit_of_measurement: 'm²'
      entity_id:
        - vacuum.roborock_s6
      value_template: "{{ states('sensor.roborock_s6_total_clean_area') | float | round(2) }}"
      icon_template: 'mdi:ruler'
    vacuum_name:
      value_template: 'Odkurzacz'

# Pilot TV
- platform: template
  sensors:
    tv_name:
      value_template: 'Telewizor'

# Yamaha Amplituner
- platform: template
  sensors:
    yamaha_name:
      value_template: 'Amplituner'

# Xiaomi Humidifier
- platform: template
  sensors:
    humidifier_name:
      value_template: 'Nawilżacz'

# Harmony Hub Remote
- platform: template
  sensors:
    harmony_name:
      value_template: 'Aktywności Harmony Hub'

# Philips Hue
- platform: template
  sensors:
    philips_hue:
      value_template: 'Oświetlenie'

# Philips Hue Motion Sensor
- platform: template
  sensors:
    hue_motion:
      value_template: 'Czujnik ruchu'

# LG washer-dryer
- platform: template
  sensors:
    pralko_suszarka:
      value_template: 'Pralko-suszarka'
    washer_cycle_state:
      value_template: "{{state_attr('sensor.pralka', 'remain_time')}}"
      friendly_name: Washer Cycle State
    washer_cycles_num:
      value_template: "{{state_attr('sensor.pralka', 'tubclean_count')}}"
      friendly_name: Washer Cycles Number
    washer_initial_time:
      value_template: "{{state_attr('sensor.pralka', 'initial_time')}}"
      friendly_name: Washer Cycle Initial Time
    washer_current_course:
      value_template: "{{state_attr('sensor.pralka', 'current_course')}}"
      friendly_name: Washer Current Course
    washer_spin_option_state:
      value_template: "{{state_attr('sensor.pralka', 'spin_option_state')}}"
      friendly_name: Washer Spin Option State
    washer_watertemp_option_state:
      value_template: "{{state_attr('sensor.pralka', 'watertemp_option_state')}}"
      friendly_name: Washer Watertemp Option State
    washer_drylevel_option_state:
      value_template: "{{state_attr('sensor.pralka', 'drylevel_option_state')}}"
      friendly_name: Washer Drylevel Option State
    washer_reserve_time:
      value_template: "{{state_attr('sensor.pralka', 'reserve_time')}}"
      friendly_name: Washer Reserve Time
      
# Optoma GT 1080e
- platform: template
  sensors:
    rzutnik_optoma:
      value_template: 'Rzutnik'

# Qnap TS-453Be
- platform: template
  sensors:
    serwer_qnap:
      value_template: 'QNAP TS-453Be'

# Raspberry Pi 4 B
- platform: template
  sensors:
    serwer_rpi:
      value_template: 'Raspberry Pi 4 B'

# Plex
- platform: plex_recently_added
  name: Recently Added Movies
  token: !secret plex_token
  host: !secret plex_host
  port: !secret plex_port
  max: 4
  section_types:
    - movie
  exclude_keywords:
    - Ewa
    - img
    
- platform: plex_recently_added
  name: Recently Added TV
  token: !secret plex_token
  host: !secret plex_host
  port: !secret plex_port
  max: 4
  section_types:
    - show
    
# Tautulli
- platform: tautulli
  api_key: !secret tautulli_api_key
  host: !secret tautulli_host
  port: !secret tautulli_port

# Yahoo finance
- platform: template
  sensors:
    eurpln_change:
      value_template: '{{ states.sensor.yahoofinance_eurpln_x.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'
      
- platform: template
  sensors:
    usdpln_change:
      value_template: '{{ states.sensor.yahoofinance_pln_x.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'
      
- platform: template
  sensors:
    gbppln_change:
      value_template: '{{ states.sensor.yahoofinance_gbppln_x.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'
      
- platform: template
  sensors:
    eurusd_change:
      value_template: '{{ states.sensor.yahoofinance_eurusd_x.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'
      
- platform: template
  sensors:
    btcusd_change:
      value_template: '{{ states.sensor.yahoofinance_btc_usd.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'
      
- platform: template
  sensors:
    ethusd_change:
      value_template: '{{ states.sensor.yahoofinance_eth_usd.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'
      
- platform: template
  sensors:
    dogeusd_change:
      value_template: '{{ states.sensor.yahoofinance_doge_usd.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'
      
- platform: template
  sensors:
    solusd_change:
      value_template: '{{ states.sensor.yahoofinance_sol_usd.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'
      
- platform: template
  sensors:
    wig20_change:
      value_template: '{{ states.sensor.yahoofinance_wig20_wa.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'
      
- platform: template
  sensors:
    wig_change:
      value_template: '{{ states.sensor.yahoofinance_wig_wa.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'
      
- platform: template
  sensors:
    sp500_change:
      value_template: '{{ states.sensor.yahoofinance_gspc.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'
      
- platform: template
  sensors:
    djia_change:
      value_template: '{{ states.sensor.yahoofinance_dji.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'
      
- platform: template
  sensors:
    ftse_change:
      value_template: '{{ states.sensor.yahoofinance_ftse.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'
      
- platform: template
  sensors:
    dax_change:
      value_template: '{{ states.sensor.yahoofinance_gdaxi.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'
      
- platform: template
  sensors:
    n225_change:
      value_template: '{{ states.sensor.yahoofinance_n225.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'
      
- platform: template
  sensors:
    sse_change:
      value_template: '{{ states.sensor.yahoofinance_000001_ss.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'
      
- platform: template
  sensors:
    gold_change:
      value_template: '{{ states.sensor.yahoofinance_gc_f.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'
      
- platform: template
  sensors:
    silver_change:
      value_template: '{{ states.sensor.yahoofinance_si_f.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'
      
- platform: template
  sensors:
    copper_change:
      value_template: '{{ states.sensor.yahoofinance_hg_f.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'
      
- platform: template
  sensors:
    oil_change:
      value_template: '{{ states.sensor.yahoofinance_bz_f.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'
      
- platform: template
  sensors:
    apple_change:
      value_template: '{{ states.sensor.yahoofinance_aapl.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'
      
- platform: template
  sensors:
    microsoft_change:
      value_template: '{{ states.sensor.yahoofinance_msft.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'
      
- platform: template
  sensors:
    alphabet_change:
      value_template: '{{ states.sensor.yahoofinance_goog.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'
      
- platform: template
  sensors:
    meta_change:
      value_template: '{{ states.sensor.yahoofinance_meta_2.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'
      
- platform: template
  sensors:
    amazon_change:
      value_template: '{{ states.sensor.yahoofinance_amzn.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'
      
- platform: template
  sensors:
    tesla_change:
      value_template: '{{ states.sensor.yahoofinance_tsla.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'
      
- platform: template
  sensors:
    buffet_change:
      value_template: '{{ states.sensor.yahoofinance_brk_b.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'
      
- platform: template
  sensors:
    jpmorgan_change:
      value_template: '{{ states.sensor.yahoofinance_jpm.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'

- platform: template
  sensors:
    aramco_change:
      value_template: '{{ states.sensor.yahoofinance_2222_sr.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'
      
- platform: template
  sensors:
    tencent_change:
      value_template: '{{ states.sensor.yahoofinance_0700_hk.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'
      
- platform: template
  sensors:
    alibaba_change:
      value_template: '{{ states.sensor.yahoofinance_9988_hk.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'
      
- platform: template
  sensors:
    tsmc_change:
      value_template: '{{ states.sensor.yahoofinance_2330_tw.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'
      
- platform: template
  sensors:
    samsung_change:
      value_template: '{{ states.sensor.yahoofinance_005930_ks.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'
      
- platform: template
  sensors:
    lvmh_change:
      value_template: '{{ states.sensor.yahoofinance_mc_pa.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'
      
- platform: template
  sensors:
    pkobp_change:
      value_template: '{{ states.sensor.yahoofinance_pko_wa.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'
      
- platform: template
  sensors:
    cdr_change:
      value_template: '{{ states.sensor.yahoofinance_cdr_wa.attributes.regularMarketChangePercent}}'
      unit_of_measurement: '%'