- platform: template
  switches:
    # Harmony Hub Remote
    # TV
    tv:
      friendly_name: TV
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Turn on TV') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'Turn on TV'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'PowerOff'

    # Optoma Movie
    optoma_movie:
      friendly_name: Optoma Movie
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Optoma Movie') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'Optoma Movie'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'PowerOff'

    # Play Station TV
    playstation_tv:
      friendly_name: Play Station TV
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Turn on PlayStation') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'Turn on PlayStation'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'PowerOff'
          
    # Netflix
    netflix:
      friendly_name: Netflix
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Turn on Netflix') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'Turn on Netflix'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'PowerOff'

    # Yamaha Gramophone
    yamh_grmph:
      friendly_name: Yamaha Gramophone
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Yamaha Gramophone') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'Yamaha Gramophone'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'PowerOff'

    # Yamaha Bluetooth
    yamh_blth:
      friendly_name: Yamaha Bluetooth
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Yamaha Bluetooth') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'Yamaha Bluetooth'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'PowerOff'

    # Yamaha Radio
    yamh_radio:
      friendly_name: Yamaha Radio
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Yamaha Radio') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'Yamaha Radio'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'PowerOff'

    # Yamaha Internet Radio
    yamh_int_radio:
      friendly_name: Yamaha Internet Radio
      value_template: "{{ is_state_attr('remote.harmony_hub', 'current_activity', 'Yamaha Internet Radio') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'Yamaha Internet Radio'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.harmony_hub
          activity: 'PowerOff'

    harmony_hub_status:
      friendly_name: Harmony Hub status
      value_template: "{{ not is_state_attr('remote.harmony_hub', 'current_activity', 'PowerOff')  }}"
      turn_on:
          service: switch.turn_on
      turn_off:
          service: switch.turn_off

    # Philips Hue Lights
    all_hue_lights_status:
      friendly_name: All hue lights status
      value_template: "{{ is_state('light.kitche_leds', 'on') or is_state('light.kitchen', 'on') or is_state('light.salon', 'on') or is_state('light.hall',  'on') or is_state('light.bathroom', 'on') }}"
      turn_on:
          service: switch.turn_on
      turn_off:
          service: switch.turn_off
   
    # LG Washer-Dryer
    lg_washer_status:
      friendly_name: LG washer status
      value_template: "{{ is_state('sensor.pralka', 'on') }}"
      turn_on:
          service: switch.turn_on
      turn_off:
          service: switch.turn_off

    # NAS TS-453Be
    nas_server_status:
      friendly_name: NAS server status
      value_template: "{{ is_state('sensor.gml_nas_smart_status_drive_0_3', 'OK') }}"
      turn_on:
          service: switch.turn_on
      turn_off:
          service: switch.turn_off
          
    # Raspberry Pi 4 B
    rpi_server_status:
      friendly_name: RPI server status
      value_template: "{{ states('sensor.rpi_temp_gml22')|float > 0 }}"
      turn_on:
          service: switch.turn_on
      turn_off:
          service: switch.turn_off      